name: notebooks-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib
  - numpy
  - pandas
  - xarray
  - netCDF4
  - pip
  - pip:
    - git+https://github.com/mwengren/notebooks-dev.git
